export type LOGIN_ACTION = 'App/Auth/LOGIN';
export const LOGIN_ACTION : LOGIN_ACTION = 'App/Auth/LOGIN';

export type LOGGED_IN_ACTION = 'App/Auth/LOGGED_IN';
export const LOGGED_IN_ACTION : LOGGED_IN_ACTION = 'App/Auth/LOGGED_IN';

export type LOGOUT_ACTION = 'App/Auth/LOGOUT';
export const LOGOUT_ACTION : LOGOUT_ACTION = 'App/Auth/LOGOUT';

export type INCREMENT_COUNTER_ACTION = 'App/Counter/INCREMENT_COUNTER';
export const INCREMENT_COUNTER_ACTION : INCREMENT_COUNTER_ACTION = 'App/Counter/INCREMENT_COUNTER';

export type DECREMENT_COUNTER_ACTION = 'App/Counter/DECREMENT_COUNTER';
export const DECREMENT_COUNTER_ACTION : DECREMENT_COUNTER_ACTION = 'App/Counter/DECREMENT_COUNTER';

export type SHOW_SPINNER_ACTION = 'App/Spinner/SHOW_SPINNER';
export const SHOW_SPINNER_ACTION : SHOW_SPINNER_ACTION = 'App/Spinner/SHOW_SPINNER';

export type HIDE_SPINNER_ACTION = 'App/Spinner/HIDE_SPINNER';
export const HIDE_SPINNER_ACTION : HIDE_SPINNER_ACTION = 'App/Spinner/HIDE_SPINNER';

