export type INCREMENT_COUNTER_ACTION = 'App/Counter/INCREMENT_COUNTER';
export const INCREMENT_COUNTER_ACTION : INCREMENT_COUNTER_ACTION = 'App/Counter/INCREMENT_COUNTER';

export type DECREMENT_COUNTER_ACTION = 'App/Counter/DECREMENT_COUNTER';
export const DECREMENT_COUNTER_ACTION : DECREMENT_COUNTER_ACTION = 'App/Counter/DECREMENT_COUNTER';
